spring.application.name=JEnterprise Backend
# Server Configuration
server.port=8088

# C?u hình MongoDB
# N?u m?t kh?u có ký t? ??c bi?t khác (ví d?: !, #, $...), b?n có th? dùng URL encoding:
# @ ? %40
# ! ? %21
# # ? %23
# $ ? %24
# % ? %25
# & ? %26
spring.data.mongodb.uri=mongodb+srv://admin:hungnt121%40gmail.com@jenterprise-cluster.50c8w.mongodb.net/JEnterprise?retryWrites=true&w=majority&appName=JENterprise-Cluster
spring.data.mongodb.socket-timeout=3000
spring.data.mongodb.connect-timeout=3000
spring.data.mongodb.min-pool-size=5
spring.data.mongodb.max-pool-size=50
spring.data.mongodb.max-connection-idle-time=60000

# Ho?c k?t n?i MongoDB Local
# spring.data.mongodb.uri=mongodb://localhost:27017/your_database_name

# C?u hình Redis
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

