spring.application.name=JEnterprise GatewayService
app.secret = app_secretkey


# URL ?? g?i các d?ch v? bên ngoài t? API Gateway
#user_service.url=http://user-service:8081
#auth_service.url=http://user-service:8081
#tour_service.url=http://tour-service:8082
#guide_service.url=http://guide-service:8083
#recommendation_service.url=http://recommendation-service:5000

user_service.url=http://ultimately-flowing-stag.ngrok-free.app/users
auth_service.url=http://ultimately-flowing-stag.ngrok-free.app/auth
tour_service.url=http://ultimately-flowing-stag.ngrok-free.app/tours
guide_service.url=http://ultimately-flowing-stag.ngrok-free.app/guides
recommendation_service.url=http://ultimately-flowing-stag.ngrok-free.app/recommendation