spring.application.name=JEnterprise GatewayService
app.secret = app_secretkey


# URL ?? g?i các d?ch v? bên ngoài t? API Gateway
#user_service.url=http://user-service:8081/api/users
#auth_service.url=http://user-service:8081/api/auth
#tour_service.url=http://tour-service:8082/api/tours
#guide_service.url=http://guide-service:8083/api/guides
#recommendation_service.url=http://recommendation-service:5000

user_service.url=http://ultimately-flowing-stag.ngrok-free.app/users
auth_service.url=http://ultimately-flowing-stag.ngrok-free.app/auth
tour_service.url=http://ultimately-flowing-stag.ngrok-free.app/tours
guide_service.url=http://ultimately-flowing-stag.ngrok-free.app/guides
recommendation_service.url=http://ultimately-flowing-stag.ngrok-free.app/recommendation

#user_service.url=http://localhost:80/users
#auth_service.url=http://localhost:80/auth
#tour_service.url=http://localhost:80/tours
#guide_service.url=http://localhost:80/guides
#recommendation_service.url=http://localhost:80/recommendation