spring.application.name=JEnterprise TourService

spring.data.mongodb.uri=mongodb+srv://admin:hungnt121%40gmail.com@jenterprise-cluster.50c8w.mongodb.net/JEnterprise?retryWrites=true&w=majority&appName=JENterprise-Cluster
spring.data.mongodb.socket-timeout=3000
spring.data.mongodb.connect-timeout=3000
spring.data.mongodb.min-pool-size=5
spring.data.mongodb.max-pool-size=50
spring.data.mongodb.max-connection-idle-time=60000
