spring.application.name=JEnterprise UserService
jwt.secret=this_is_my_secret_key_for_jwt_service_in_org.java_enterprise.backend.user_service
app.secret = app_secretkey

spring.data.mongodb.uri=mongodb+srv://admin:hungnt121%40gmail.com@jenterprise-cluster.50c8w.mongodb.net/JEnterprise?retryWrites=true&w=majority&appName=JENterprise-Cluster
spring.data.mongodb.socket-timeout=3000
spring.data.mongodb.connect-timeout=3000
spring.data.mongodb.min-pool-size=5
spring.data.mongodb.max-pool-size=50
spring.data.mongodb.max-connection-idle-time=60000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=botspammer741@gmail.com
spring.mail.password=tdtu@1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true