# -*- coding: utf-8 -*-
"""RecommendationSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ch9rvnYBepy0KekltTNYss9qyNSVZroa
"""

!python -m pip install "pymongo[srv]"==3.11
!pip install requests
!pip install googletrans==4.0.0-rc1
!pip install SPARQLWrapper

import requests
import json

import certifi
from pymongo import MongoClient
from urllib.parse import quote_plus

import pandas as pd
from googletrans import Translator
import time
from IPython.display import clear_output

import re
from SPARQLWrapper import SPARQLWrapper, JSON

# Cấu hình MongoDB
USER = "admin"
PASS = quote_plus("hungnt121@gmail.com")  # Encode password
HOST = "jenterprise-cluster.50c8w.mongodb.net"
DB_NAME = "JEnterprise"
TOURS_TABLE = "tours"

# MONGO_URI = f"mongodb+srv://{USER}:{PASS}@{HOST}/{DB_NAME}?retryWrites=true&w=majority"
MONGO_URI = f"mongodb+srv://{USER}:{PASS}@{HOST}/{DB_NAME}?retryWrites=true&w=majority&appName=JENterprise-Cluster"

sparql = SPARQLWrapper("https://query.wikidata.org/sparql")

def getFirstTourInfo():
  global MONGO_URI, DB_NAME, TOURS_TABLE
  try:
      client = MongoClient(MONGO_URI, tls=True, tlsAllowInvalidCertificates=True)
      db = client[DB_NAME]
      collection = db[TOURS_TABLE]
      items = []
      return collection.find_one()
  except Exception as e:
      print(f"❌ Lỗi kết nối MongoDB: {e}")
      return

tour_info = getFirstTourInfo()

print(tour_info)

"""### USING LOOKUP For get location list - only work if vietnamese place"""

def extract_earth_places():
  df = pd.read_csv('worldcities/worldcities.csv')
  df = df[['city', 'country', 'admin_name']]
  unique_countries = df['country'].unique()

  # Initialize translator
  translator = Translator()
  translated_dict = {}

  # Loop with progress and screen clearing
  total = len(unique_countries)
  for i, country in enumerate(unique_countries):
      try:
          translated = translator.translate(country, src='en', dest='vi')
          translated_dict[country] = translated.text
      except Exception as e:
          translated_dict[country] = country  # fallback if error
      # Display progress
      percent = round((i + 1) / total * 100, 2)
      clear_output(wait=True)
      print(f"{percent}% - {country}-{translated_dict[country]}")

      # Optional: avoid rate limit
      time.sleep(0.1)

  # Map translations to DataFrame
  clear_output(wait=True)
  df['country_vi'] = df['country'].map(translated_dict)
  return df

"""##### Special Heritage"""

sp_all_results = []
sp_offset = 0
sp_limit = 5000

def remove_in_location(place, location):
    if location and re.search(rf"\bin\s+{re.escape(location)}\b", place, re.IGNORECASE):
        # Xóa phần "in [location]" khỏi placeLabel
        return re.sub(rf"\s*\bin\s+{re.escape(location)}\b", "", place, flags=re.IGNORECASE).strip()
    return place

# Lấy danh lam thắng cảnh với spasql
def extract_next_special_places():
  global sparql,sp_all_results,sp_offset,sp_limit
  # Bắt đầu vòng lặp
  try:
    # Thực hiện truy vấn
    sparql.setQuery(f"""
    SELECT ?placeLabel ?locationLabel ?countryLabel WHERE {{
        ?place wdt:P31/wdt:P279* wd:Q570116.
        OPTIONAL {{ ?place wdt:P131 ?location. }}
        OPTIONAL {{ ?place wdt:P17 ?country. }}
        SERVICE wikibase:label {{ bd:serviceParam wikibase:language "vi,en". }}
      }}
      LIMIT {sp_limit} OFFSET {sp_offset}
    """)
    sparql.setReturnFormat(JSON)

    # Gửi truy vấn và xử lý dữ liệu
    results = sparql.query().convert()

    # Chuyển kết quả thành DataFrame
    result_list = results["results"]["bindings"]
    if result_list:
      for result in result_list:
        place = result.get("placeLabel", {}).get("value", "")
        location = result.get("locationLabel", {}).get("value", "")
        country = result.get("countryLabel", {}).get("value", "")
        if not place or not country or re.fullmatch(r"Q\d+", place):
          continue
        place = remove_in_location(place, location)
        result_data = {"location": place, "city": location, "country": country}
        sp_all_results.append(result_data)
        clear_output(wait=True)
        print(f"{len(sp_all_results)}-{result_data}")
        # Optional: avoid rate limit
        time.sleep(0.2)

    # Nếu ít hơn 1000 kết quả, dừng lại
    if len(result_list) < sp_limit:
        return False

    # Cập nhật offset cho lần truy vấn tiếp theo
    sp_offset += sp_limit
  except:
    return False

  return True

def merge_df_with_world_places(world_places, world_special_places):
  # First, try merging using English country name
  merge1 = pd.merge(world_special_places, world_places, on=['city', 'country'], how='left')
  # Then try merging using Vietnamese name
  # For this, rename `country_vi` to `country` temporarily to match column
  # st_vi = world_places.drop(columns=['country']).rename(columns={'country_vi': 'country'})
  # merge2 = pd.merge(world_special_places, st_vi, on=['city', 'country'], how='left')
  merge2 = pd.merge(world_places, world_special_places, left_on=['city', 'country_vi'], right_on=['city', 'country'], how='left')

  # Combine results: prefer merge1 where data is not null, otherwise use merge2
  finaldff = merge1.combine_first(merge2)

  # Fill missing values with 'unknown'
  finaldff = finaldff.rename(columns={'location': 'heritage'})
  finaldff['admin_name'] = finaldff['admin_name'].fillna('')
  finaldff['country_vi'] = finaldff['country_vi'].fillna('')
  finaldff['heritage'] = finaldff['heritage'].fillna('Không có danh lam thắng cảnh')

  # Ensure final column order
  finaldff = finaldff[['city', 'country', 'admin_name', 'country_vi', 'heritage']]
  return finaldff

"""#### Example"""

world_places = extract_earth_places()
world_places

while extract_next_special_places():
  pass

world_special_places = pd.DataFrame(sp_all_results)
world_special_places

merge_df_with_world_places(world_places, world_special_places)

"""##### Old version"""

VIETNAM_PLACES = [
    "Hà Nội", "Hồ Chí Minh", "Đà Nẵng", "Hải Phòng", "Cần Thơ",
    "An Giang", "Bà Rịa - Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu",
    "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước",
    "Bình Thuận", "Cà Mau", "Cao Bằng", "Đắk Lắk", "Đắk Nông",
    "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang",
    "Hà Nam", "Hà Tĩnh", "Hải Dương", "Hậu Giang", "Hòa Bình",
    "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu",
    "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định",
    "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên",
    "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh",
    "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình",
    "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang",
    "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái",

    # Danh lam thắng cảnh
    "Vịnh Hạ Long", "Quần thể danh thắng Tràng An", "Cố đô Hoa Lư", "Đỉnh Fansipan",
    "Sapa", "Vườn quốc gia Phong Nha – Kẻ Bàng", "Hang Sơn Đoòng", "Thánh địa Mỹ Sơn",
    "Phố cổ Hội An", "Cố đô Huế", "Chùa Thiên Mụ", "Lăng Tự Đức",
    "Chợ Đông Ba", "Đảo Phú Quốc", "Mũi Né", "Đà Lạt",
    "Thung lũng Tình Yêu", "Hồ Xuân Hương", "Bà Nà Hills", "Cầu Rồng",
    "Biển Mỹ Khê", "Núi Bà Đen", "Chợ nổi Cái Răng", "Suối Tiên",
    "Bãi biển Nha Trang", "Thác Bản Giốc", "Hồ Gươm", "Văn Miếu – Quốc Tử Giám",
    "Lăng Chủ tịch Hồ Chí Minh", "Hoàng thành Thăng Long", "Thành nhà Hồ", "Tam Cốc – Bích Động",
    "Mộc Châu", "Hồ Ba Bể", "Tháp Chàm Poklong Garai", "Thánh thất Cao Đài Tây Ninh",
    "Bến Nhà Rồng", "Nhà thờ Đức Bà", "Chợ Bến Thành"
]

def extract_places_v1(text):
  global VIETNAM_PLACES
  text = text.lower()
  return [place for place in VIETNAM_PLACES if place.lower() in text]

"""### Run example"""

extract_places_v1(f"{tour_info}")