spring.application.name=JEnterprise Backend
# Server Configuration
server.port=8088

# C?u hình MongoDB
# N?u m?t kh?u có ký t? ??c bi?t khác (ví d?: !, #, $...), b?n có th? dùng URL encoding:
# @ ? %40
# ! ? %21
# # ? %23
# $ ? %24
# % ? %25
# & ? %26
spring.data.mongodb.uri=mongodb+srv://admin:hungnt121%40gmail.com@jenterprise-cluster.50c8w.mongodb.net/JEnterprise?retryWrites=true&w=majority&appName=JENterprise-Cluster
spring.data.mongodb.socket-timeout=3000
spring.data.mongodb.connect-timeout=3000
spring.data.mongodb.min-pool-size=5
spring.data.mongodb.max-pool-size=50
spring.data.mongodb.max-connection-idle-time=60000

# VnPay Configuration
vnpay.version=2.1.0
vnpay.command=pay
vnpay.tmnCode=JVFCAPRB
vnpay.currCode=VND
vnpay.locale=vn
vnpay.hashSecret=VSLF0V9RFLK86545V62BNTZN20G2PZED
vnpay.baseUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment-callback.returnUrl=http://localhost:8088/api/pay/execute
timezone.id=Asia/Ho_Chi_Minh

# CORS config
app.cors.allowed-origins=http://localhost:8088,http://localhost:5173,http://pure-calf-lively.ngrok-free.app,


